### ISSUE TITLE
Enable TTS wihtout Google play services on android (help wanted)

### ISSUE THREAD

**Issue by wuxialearn** [wuxialearn/wuxialearn#5]
Currently TTS does not work without google play services. Apps like https://github.com/benjaminwan/ChineseTtsTflite work without Google play services but I can't seem to figure out how to make https://pub.dev/packages/flutter_tts detect it being installed. https://f-droid.org/en/packages/com.danefinlay.ttsutil/ is able to detect ChineseTtsTflite and call into it without Gplay so it should be possible in theory.

**Comment by wuxialearn** [comment]
Turns out this actually always worked without google play services. It does however require "Speech Recognition and Synthesis from Google" to work which I had disabled.

**Comment by Klariios6** [comment]
Ahhh just saw this, I'll take a look and let you know of it worked. Thank you!

**Comment by Klariios6** [comment]
> Turns out this actually always worked without google play services. It does however require "Speech Recognition and Synthesis from Google" to work which I had disabled.

Did you ever enable it? Or is there a way it could work? I'd love to help!
